name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        id: go
        uses: actions/setup-go@v4
        with:
          go-version: "stable"

      - name: Restore bin
        uses: actions/cache@v3
        with:
          path: ./bin
          key: ${{ runner.os }}-go-${{ steps.go.outputs.go-version }}-bin-${{ hashFiles('**/go.sum', 'Makefile') }}

      - name: Run linter
        run: make lint

      - name: Cache bin
        uses: actions/cache@v3
        with:
          path: ./bin
          key: ${{ runner.os }}-go-${{ steps.go.outputs.go-version }}-bin-${{ hashFiles('**/go.sum', 'Makefile') }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        id: go
        uses: actions/setup-go@v4
        with:
          go-version: "stable"

      - name: Restore bin
        uses: actions/cache@v3
        with:
          path: ./bin
          key: ${{ runner.os }}-go-${{ steps.go.outputs.go-version }}-bin-${{ hashFiles('**/go.sum', 'Makefile') }}

      - name: Run tests
        run: make test

      - name: Cache bin
        uses: actions/cache@v3
        with:
          path: ./bin
          key: ${{ runner.os }}-go-${{ steps.go.outputs.go-version }}-bin-${{ hashFiles('**/go.sum', 'Makefile') }}
